### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.
spring:
  profiles:
    active:
      benefit
 
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-host1:8761/eureka/,http://eureka-host2:8762/eureka/
    instance:
      preferIpAddress: true
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}

 
 